config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Blazer::Engine, at: "blazer"

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/commercial'
  get 'pages/residential'
  get 'pages/quote'
  get '/interventions' => 'intervention#intervention'
  get 'find_buildings' => 'intervention#find_buildings'
  get 'find_batteries' => 'intervention#find_batteries'
  get 'find_columns' => 'intervention#find_columns'
  get 'find_elevators' => 'intervention#find_elevators'
  post '/interventions', to: 'intervention#create'
  post '/leads', to: 'leads#create'  
  get 'dropbox/auth_callback' => 'dropbox#auth_callback'

  resources :interventions
  resources :quotes
  resources :leads

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new 
    if user.supervisor_role?
          can :manage, :all
          can :access, :rails_admin     
          can :manage, :dashboard         
    end
    if user.user_role?
          can :read, :all
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/battery.rb
class Battery < ApplicationRecord
    has_many :columns
    belongs_to :building
end

app/models/building.rb
class Building < ApplicationRecord
    belongs_to :customer, foreign_key: "customer_id"
    has_many :building_details
    has_many :batteries
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery, foreign_key: "battery_id"
    has_many :elevators
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :user, foreign_key: "user_id"
    has_many :buildings

end

app/models/dim_customer.rb
class DimCustomer < DwhRecord
end

app/models/dwh_record.rb
class DwhRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :"dwh_#{Rails.env}"
end

app/models/elevator.rb
class Elevator < ApplicationRecord
    belongs_to :column , foreign_key: "column_id"
    after_update :contact_tech

    def contact_tech
        if self.status == "Intervention" or self.status == "intervention"
            message = "The Elevator, ID: #{self.id}, in building: #{self.column.battery.building.id}, on #{self.column.battery.building.address_building} needs maintenance"
            TwilioText.new(message).txt
        end
    end

    around_update :update_slack

    def update_slack
        notify = self.status_changed?
        if notify
            notifier = Slack::Notifier.new ENV['SLACK_WEBHOOK_URL']
            notifier.ping "The Elevator #{self.id} with Serial Number: #{self.serial_number} changed status from : #{self.status_was} to #{self.status}"
        end
    end
end

app/models/employee.rb
class Employee < ApplicationRecord  
    belongs_to :user, foreign_key: "user_id"
end

app/models/fact_contact.rb
class FactContact < DwhRecord
end

app/models/fact_quote.rb
class FactQuote < DwhRecord
end

app/models/intervention.rb
class Intervention < ApplicationRecord
  end

app/models/lead.rb
class Lead < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :employees
  has_many :customers
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocket Elevators</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <script>var plugin_path = '/assets/plugins/';</script>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  
  </head>

  <body>

  <%= render "pages/header" %>
    
  <%= yield %>
  
    
  </body>
</html>

app/views/pages/_header.html.erb
    <div>
        <!-- WRAPPER -->
		<div id="wrapper">

			<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

        <!-- TOP NAV -->
        <header id="topNav">
            <div class="container">
                <!-- Mobile Menu Button -->
                <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Logo -->
                <%= link_to image_tag('logo-transparent.png'), root_path, :alt => "Rocket Elevators logo", :class => "logo float-left scrollTo" %>
                <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                    <nav class="nav-main">
                        <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                            <li class="active"><!-- HOME -->
                                <%= link_to "HOME",root_path, :id => "home-nav" %>
                            </li>
                            <li>
								<a id="service-nav" href="#services">SERVICES</a>    
								<ul class="dropdown-menu">
									<li><%= link_to "Services",root_path(:anchor => "services"), class: "dropdown-item" %></li>
									<div class="dropdown-divider"></div>
									<li><%= link_to "Corporate Buildings",pages_commercial_url, class: "dropdown-item" %></li>
									<li><%= link_to "Residential Buildings",pages_residential_url, class: "dropdown-item" %></li>
									<li><%= link_to "Request a Quote",pages_quote_url, class: "dropdown-item" %></li>
								</ul>    
							</li>
                            <li><!-- PORTFOLIO -->
                                <%= link_to "PORTFOLIO",root_path(:anchor => "portfolio") %>
                            </li>
                            <li><!-- NEWS -->
                                <%= link_to "NEWS",root_path(:anchor => "news") %>
                            </li>
                            <li><!-- CLIENTS -->
                                <%= link_to "CLIENTS",root_path(:anchor => "clients") %>
                            </li>
                            <li><!-- CONTACT -->
                                <%= link_to "CONTACT",root_path(:anchor => "contact") %>
                            </li>
                            <% if user_signed_in? && current_user.supervisor_role? %>
								<li><!--Intervention -->
									<%= link_to "INTERVENTION", interventions_url%>
								</li>
								<li><!-- ADMIN -->
									<%= link_to "ADMIN", rails_admin_url %>
								</li>
								<li><!-- LOGOUT -->
									<%= link_to "LOGOUT", destroy_user_session_path, method: :delete %>
								</li>
							<% elsif user_signed_in? %>
								<li><!-- LOGOUT -->
									<%= link_to "LOGOUT", destroy_user_session_path, method: :delete %>
								</li>
							<% else %>
								<li><!-- LOGIN -->
									<%= link_to "LOGIN", new_user_session_path %>
								</li>
							<% end %>
                        </ul>

                    </nav>
                </div>
            </div>
        </header>
    </div>
        <!-- /Top Nav -->

app/views/pages/commercial.html.erb
	<!-- INTRO -->
	<div class="slider fullwidthbanner-container roundedcorners">
		<div id="home" class="fullwidthbanner" data-delay="0" data-height="600" data-shadow="0" data-navigationStyle="preview2">
			<ul class="hide">
				<li data-transition="parallaxtobottom" data-slotamount="7" data-masterspeed="300"  data-saveperformance="off"  data-title="Our Values">
					<!-- MAIN IMAGE -->
					<img src="/assets/elevator-glass-cylinder.jpeg"  alt="cover image"  data-bgposition="center" data-bgfit="cover" data-bgrepeat="no-repeat">
				</li>
			</ul>
		</div>
	</div>

	<a href="#contact" class="btn btn-xlg btn-primary fs-20 fullwidth m-0 rad-0 p-40">
		<span class="font-lato fs-30">
			<strong>
				Elevate Safety, Speed and Style in Commercial, Corporate or Hybrid Buildings
			</strong>
		</span>
	</a>
	<!-- INTRO -->

	<!-- TECHNOLOGY -->
	<section id="technology">
		<div class="container">
			<div class="heading-title heading-dotted text-center">
				<h2>Our Talent and Creativity at Your Service!</h2>
			</div>
			<h3 class="text-center">
				Advanced Technology
			</h3>
			<div>
				<p>
					Rocket Elevators has been deploying elevator services in commercial, corporate and hybrid buildings that 
					mix residential and commercial spaces for more than 40 years. Given to raising our industry's
					standards, we propose a technology equivalent to none in terms of comfort and silence, performance, safety 
					and reliability.
				</p>
				<p>	
					That is why we were the first to bring artificial intelligence to air quality control
					and were the first to extend that technology to all our products. That's how we constantly push the elevator's world 
					to reinvent itself!
				</p> 
				<p>
					That is also why we developed advanced people flow solutions that offer both scalable and 
					flexible access control and seamlessly integrate with your elevator system and building doors. 
				</p>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12">
						<%= image_tag 'elevator-open.jpeg', alt: "elevator pic", width: "100%" , height: "399", class:"img-fluid" %>
					</a>
					<h3 class="mt-10 text-center">Access</h3>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
						<%= image_tag 'destination-control.png', alt: "destination control pic", width: "100%", class: "img-fluid" %>
					</a>
					<h3 class="mt-10 text-center">Direction</h3>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
						<%= image_tag 'infotainment.png', alt: "lady in elevator", width: "100%", class: "img-fluid" %>
					</a>
					<h3 class="mt-10 text-center">Infotainment</h3>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
						<%= image_tag 'flow-monitoring.png', alt: "computer monitoring", width: "100%", class: "img-fluid" %>
					</a>
					<h3 class="mt-10 text-center">Monitoring</h3>
				</div>
			</div>
			<div class="text-center">
				<a class="btn btn-primary btn-lg" href="quote.html" target="_self">GET A QUOTE <i class="fa fa-angle-right"></i></a>
			</div>
		</div>
	</section>
	<!-- /TECHNOLOGY -->

	<div class="parallax parallax-1">
		<%= image_tag 'project-management2', alt: "project management cycle", width: "100%", class: "img-fluid" %>
	</div>
				
	<!-- PLANNING -->
	<section id="commercial-planning">
		<div class="container">
			<div class="heading-title heading-dotted text-center">
				<h2><em>Rocket</em> Solid Planning</h2>
			</div>
			<div>
				<p>
					Our job is to make <em>your</em> job easier. And since this starts with good communication, our pledge at Rocket Elevators 
					is first and foremost to <em>listen</em> to you and <em>your</em> needs to get a perfect grasp of 
					<em>your</em> project. From then on, we'll make sure everything is in place for a smooth, 
					trouble-free elevator installation process to keep your project on schedule and on budget, with no surprises.
				</p>
				<p>
					Depending on the nature of your project, this will start with collecting the following key pieces of information:
				</p>
				<div class="container">
					<div class="row mb-10">
						<div id="commercial-data" class="col-md-8 col-sm-12 mt-0 mb-0">
							<h3 class="mt-0">Commercial Building</h3>
							<ul>
								<li>The number of distinct businesses</li>
								<li>The number of floors in the building</li>
								<li>The number of basements</li>
								<li>The number of parking spaces available</li>
								<li>The number of elevator cages to be deployed</li>
							</ul> 
						</div>
						<div class="col-md-4 col-sm-12 mt-30 mb-10">
							<%= image_tag 'shopping-mall-elevator2', alt: "commercial building", width: "100%", height: "150px" %>
						</div>
					</div>
					<div class="row mb-10">
						<div id="corporate-data" class="col-md-8 col-sm-12 mt-0 mb-0">
							<h3 class="mt-0">Corporate Building</h3>
							<ul>
								<li>The number of separate tenant companies</li>
								<li>The number of floors in the building</li>
								<li>The number of basements</li>
								<li>The number of parking spaces available</li>
								<li>The maximum number of occupants per floor</li>
							</ul> 
						</div>
						<div class="col-md-4 col-sm-12 mt-30 mb-10">
							<%= image_tag 'corporate-building-elevator2.png', alt: "corporate building", width: "100%",  height: "150px" %>
						</div>
					</div>
					<div class="row mb-10">
						<div id="hybrid-data" class="col-md-8 col-sm-12 mt-0 mb-0">
							<h3 class="mt-0">Hybrid Building</h3>
							<ul>
								<li>The number of distinct businesses</li>
								<li>The number of floors in the building</li>
								<li>The number of basements</li>
								<li>The number of parking spaces available</li>
								<li>The maximum number of occupants per floor</li>
								<li>The number of hours of daily commercial and/or corporate activity of the building</li>
							</ul> 
						</div>
						<div class="col-md-4 col-sm-12 mt-30 mb-10">
							<%= image_tag 'hybrid-building.png', alt: "corporate building", width: "100%",  height: "150px" %>
						</div>
					</div>
				</diV>
				<h3 class="text-center mt-20">
					With Rocket Elevators planning, <br> your project is on the fast track to success!
				</h3>
				<br>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-lg-4 col-md-4 col-sm-12">
							<%= image_tag 'effective-project-kickoff.jpg', alt: "team meeting pic", width: "100%", class:"img-fluid" %>
						</a>
						<h3 class="mt-10 text-center">Your Plan, Our Plan</h3>
					</div>

					<div class="col-lg-4 col-md-4 col-sm-12">
							<%= image_tag 'on-time-on-budget2.png', alt: "dollar-clock pic", width: "100%", class:"img-fluid" %>
						</a>
						<h3 class="mt-10 text-center">On Time, Within Budget</h3>
					</div>

					<div class="col-lg-4 col-md-4 col-sm-12">
							<%= image_tag 'elevator-maintenance.jpeg', alt: "workers pic", width: "100%", class:"img-fluid" %>
						</a>
						<h3 class="mt-10 text-center">By Professionals</h3>
					</div>
				</div>
			</div>
		</div>

	</section>
	<!-- /PLANNING -->
	
	<!-- FOUNDATION -->
	<section class="parallax parallax-1" style="background-image: url(<%= image_path "elavator-cityview-crop.jpg"%>)">
		<div class="overlay dark-5"></div>
		<div class="container">
			<div class="text-center">
				<h2 class="fs-40 fw-300">Elevating Quality Since 1976</h2>
				<a class="btn btn-default btn-lg" href="quote.html" target="_self">GET A QUOTE <i class="fa fa-angle-right"></i></a>
				&nbsp; &nbsp;
				<%= link_to "CONTACT US",root_path(:anchor => "contact"), class:"btn btn-primary btn-lg" %>
			</div>
		</div>
	</section>


	<!-- FOOTER -->
	<footer id="footer">
		<div class="container mt-0 mb-30">
			<div class="row">
				<!-- col #1 -->
				<div class="col-md-7">
					<h3 class="letter-spacing-1">WHY US?</h3>
					<!-- Small Description -->
					<p>
						We have the conviction that we create the most innovative and reliable products on the market. </br>
						Contact us today for any questions you might have.
					</p>
				</div>
				<!-- /col #1 -->
				<!-- col #2 -->
				<div class="col-md-5">
					<h3>(418) 555-1234</h3>
					<p>
						<span class="block"><strong><i class="fa fa-map-marker"></i> 418-725 Boulevard Lebourgneuf, Québec, QC G2J 0C4, Canada</span>
						<span class="block"><strong><i class="fa fa-envelope"></i> Email:</strong> <a href="mailto:info@codeboxx.biz">info@codeboxx.biz</a></span>
					</p>
				</div>
				<!-- /col #2 -->
			</div>
		</div>
		<div class="copyright">
			<div class="container">
				&copy; All Rights Reserved
			</div>
		</div>
	</footer>
	<!-- /FOOTER -->
</div>
<!-- /wrapper -->

<!-- SCROLL TO TOP -->
<a href="#" id="toTop"></a>

app/views/pages/intervention.html.erb
<!-- WRAPPER -->
		<div id="wrapper">

			<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

        <!-- TOP NAV -->
        <header id="topNav">
            <div class="container">
                <!-- Mobile Menu Button -->
                <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Logo -->
                <%= link_to image_tag('logo-transparent.png'), root_path, :alt => "Rocket Elevators logo", :class => "logo float-left scrollTo" %>
                <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                    <nav class="nav-main">
                        <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                            <li class="active"><!-- HOME -->
                                <%= link_to "HOME",root_path, :id => "home-nav" %>
                            </li>
                            <li>
								<a id="service-nav" href="#services">SERVICES</a>    
								<ul class="dropdown-menu">
									<li><%= link_to "Services",root_path(:anchor => "services"), class: "dropdown-item" %></li>
									<div class="dropdown-divider"></div>
									<li><%= link_to "Corporate Buildings",pages_commercial_url, class: "dropdown-item" %></li>
									<li><%= link_to "Residential Buildings",pages_residential_url, class: "dropdown-item" %></li>
									<li><%= link_to "Request a Quote",pages_quote_url, class: "dropdown-item" %></li>
								</ul>    
							</li>
                            <li><!-- PORTFOLIO -->
                                <%= link_to "PORTFOLIO",root_path(:anchor => "portfolio") %>
                            </li>
                            <li><!-- NEWS -->
                                <%= link_to "NEWS",root_path(:anchor => "news") %>
                            </li>
                            <li><!-- CLIENTS -->
                                <%= link_to "CLIENTS",root_path(:anchor => "clients") %>
                            </li>
                            <li><!-- CONTACT -->
                                <%= link_to "CONTACT",root_path(:anchor => "contact") %>
                            </li>
                            <% if user_signed_in? && current_user.supervisor_role? %>
								<li><!--Intervention -->
									<%= link_to "INTERVENTION", pages_intervention_url%>
								</li>
								<li><!-- ADMIN -->
									<%= link_to "ADMIN", rails_admin_url %>
								</li>
								<li><!-- LOGOUT -->
									<%= link_to "LOGOUT", destroy_user_session_path, method: :delete %>
								</li>
							<% elsif user_signed_in? %>
								<li><!-- LOGOUT -->
									<%= link_to "LOGOUT", destroy_user_session_path, method: :delete %>
								</li>
							<% else %>
								<li><!-- LOGIN -->
									<%= link_to "LOGIN", new_user_session_path %>
								</li>
							<% end %>
                        </ul>

                    </nav>
                </div>
            </div>
        </header>
        <!-- /Top Nav -->
			</div>

app/views/shared/_navbar.html.erb
<!-- WRAPPER -->
		<div id="wrapper">

			<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

        <!-- TOP NAV -->
        <header id="topNav">
            <div class="container">
                <!-- Mobile Menu Button -->
                <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Logo -->
                <%= link_to image_tag('logo-transparent.png'), root_path, :alt => "Rocket Elevators logo", :class => "logo float-left scrollTo" %>
                <!--<a class="logo float-left scrollTo" href="index.html" target="_self">
                    <%= image_tag 'logo-transparent.png', alt: "Rocket Elevators logo" %>
                    <img src="assets/images/logo-transparent.png" alt="Rocket Elevator logo" />
                </a>-->
                <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                    <nav class="nav-main">
                        <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                            <li class="active"><!-- HOME -->
                                <%= link_to "HOME",root_path, :id => "home-nav" %>
                                <!--<a id="home-nav" href="index.html" target="_self">
                                    HOME
                                </a>-->
                            </li>
                            <li>
                                <div class="dropdown">
                                    <button class="nav nav-pills nav-main nav-onepage dropdown-toggle" type="button" id="services-nav" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        SERVICES
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="services-nav">
                                        <a id="services-nav" class="dropdown-item" href="index.html#services">Services</a>
                                        <div class="dropdown-divider"></div>
												<%= link_to "Corporate Buildings",pages_commercial_url, class: "dropdown-item" %>
												<%= link_to "Residential Buildings",pages_residential_url, class: "dropdown-item" %>
												<%= link_to "Request a Quote",pages_quote_url, class: "dropdown-item" %>
                                    </div>
                                  </div>
                            </li>
                            <li><!-- PORTFOLIO -->
                                <%= link_to "PORTFOLIO",root_path(:anchor => "portfolio") %>
                                <!--<a id="portfolio-nav" href="index.html#portfolio" target="_self">
                                    PORTFOLIO
                                </a>-->
                            </li>
                            <li><!-- NEWS -->
                                <%= link_to "NEWS",root_path(:anchor => "news") %>
                                <!--<a id="news-nav" href="index.html#news" target="_self">
                                    NEWS
                                </a>-->
                            </li>
                            <li><!-- CLIENTS -->
                                <%= link_to "CLIENTS",root_path(:anchor => "clients") %>
                                <!--<a id="clients-nav" href="index.html#clients" target="_self">
                                    CLIENTS
                                </a>-->
                            </li>
                            <li><!-- CONTACT -->
                                <%= link_to "CONTACT",root_path(:anchor => "contact") %>
                                <!--<a id="contact-nav" href="#contact">
                                    CONTACT
                                </a>-->
                            </li>
                        </ul>

                    </nav>
                </div>
            </div>
        </header>
        <!-- /Top Nav -->